--- # handlers playbook
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh


  tasks:
    - name: Installing httpd on both the hosts
      yum:
        name: httpd
        state: present
      notify: starting httpd service




  handlers:
    - name: starting httpd service
      service:
        name: httpd
        state: started
