---
- hosts: webservers
  become: true
  connection: ssh
  user: ansible

  vars_files:
      user.yml


  tasks:
    - name: creating user {{user2}}
      user:
        name: '{{user2}}'
        state: present
